# Информация о приложении
info:
  name: '@project.name@'
  description: '@project.description@'
  version: '@project.version@'
  time: '@maven.build.timestamp@'

# Параметры приложения
app:
  serviceName: ${info.name}

# Параметры spring
spring:
  # profiles: prod
  application:
    name: ${info.name}
  main:
    allow-bean-definition-overriding: true
    banner-mode: "console"
    log-startup-info: true
#  kafka:
#    bootstrap-servers:
#    client-id: ${info.name}
#    consumer:
#      auto-commit-interval:
#      auto-offset-reset: latest
#      enable-auto-commit:
#      fetch-max-wait:
#      fetch-min-size:
#      group-id:
#      heartbeat-interval:
#      isolation-level:
#      key-deserializer:
#      max-poll-records:
#      properties:
#      value-deserializer:
#    listener:
#      ack-count:
#      ack-mode:
#      ack-time:
#      concurrency:
#      idle-event-interval:
#      missing-topics-fatal:
#      monitor-interval:
#      no-poll-threshold:
#      poll-timeout:
#      type:
#    producer:
#      acks:
#      batch-size:
#      buffer-memory:
#      compression-type:
#      key-serializer:
#      properties:
#      retries:
#      transaction-id-prefix:
#      value-serializer:
#    properties:
#    security:
#      protocol:
#    ssl:
#      key-password:
#      key-store-location:
#      key-store-password:
#      key-store-type:
#      protocol:
#      trust-store-location:
#      trust-store-password:
#      trust-store-type:
#    template:
#      default-topic:
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    deserialization:
#    locale:
#     mapper:
#     mapper:
#     parser:
#     property-naming-strategy:
#     serialization:
#     time-zone:
#  datasource:
#    name:
#    username:
#    password:
#    schema:
#    url:
#    hikari:
#      allow-pool-suspension
#      auto-commit:
#      catalog:
#      connection-init-sql:
#      connection-test-query:
#      connection-timeout:
#      data-source-class-name:
#      data-source-j-n-d-i:
#      data-source-properties:
#      driver-class-name:
#      exception-override-class-name:
#      health-check-properties:
#      health-check-registry:
#      idle-timeout:
#      initialization-fail-timeout:
#      isolate-internal-queries:
#      jdbc-url:
#      leak-detection-threshold:
#      login-timeout:
#      max-lifetime:
#      maximum-pool-size:
#      metric-registry:
#      metrics-tracker-factory:
#      minimum-idle:
#      password:
#      pool-name:
#      read-only:
#      register-mbeans:
#      scheduled-executor:
#      schema:
#      transaction-isolation:
#      username:
#      validation-timeout:
#  jpa:
#    show-sql: false
#  r2dbc:
#    name:
#    password:
#    url:
#    username:
#    pool:
#      enabled: true
#      initial-size: 10
#      max-idle-time: 30m
#      max-size: 20
#      validation-query: SELECT 1
#  flyway:


# Параметры http-сервера
server:
  port: 8080
  compression:
    enabled: false
  error:
    include-binding-errors: never
    include-exception: false
    include-message: never
    include-stacktrace: never
    whitelabel.enabled: true
  http2.enabled: true
  max-http-header-size: 8KB

# Логирование
debug: false
trace: false
logging:
  level:
    ru.rshb: ${APP_LOG_LEVEL_RU_RSHB:TRACE}
    ru.rshbintech: ${APP_LOG_LEVEL_RU_RSHBINTECH:TRACE}
    ru:
      rshbintech:
        integrations:
          cki:
            ip2_services:
              integration_app:
                Controller: ${APP_LOG_LEVEL_TRUE_PRODUCTION:TRACE}
    org.springframework: ${APP_LOG_LEVEL_SPRINGFRAMEWORK:INFO}

# Параметры админских эндпоинтов
management:
  endpoints:
    web:
      exposure.include:
        - health
        - loggers
        - prometheus
        - info
        - mappings
        - flyway
      base-path: /
      path-mapping:
        prometheus: metrics
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      show-details: always
      show-components: always
      group:
        liveness.include: ["*"]
        readiness.include: ["*"]
    loggers.enabled: true
    info.enabled: true
    mappings.enabled: true
    prometheus.enabled: true
    metrics.enabled: false
    beans.enabled: false
    logfile.enabled: false
    caches.enabled: false
    conditions.enabled: false
    configprops.enabled: false
    httptrace.enabled: false
    threaddump.enabled: false
    heapdump.enabled: false
    auditevents.enabled: false
    flyway.enabled: true
  health:
    defaults.enabled: false
    probes.enabled: true
    ping.enabled: true
  metrics:
    # Метрики на все входящие запросы по времени и количеству запросов
    # в разрезе эндпоинтов (префикс http.server.requests)
    web.server.request.autotime:
      enabled: true
      percentiles-histogram: true
    web.client.request.autotime:
      percentiles-histogram: true
    tags:
      app: ${info.name}

# Параметры генерации OAS-спецификации сервиса
springdoc:
  api-docs:
    resolve-schema-properties: true
    path: /api
  swagger-ui:
    path: /api/doc
    layout: BaseLayout
    display-request-duration: true
    show-extensions: true
    show-common-extensions: true

# Параметры синхронного конвертора
sync-converter:
  clean-pool-minutes: 3
  timeout:
    min: 10
    target: 60000
    max: 86400000
  pooling-interval:
    min: 1
    target: 30
    max: 3600000
